Repository keyboardio/Chrysalis, pull requests merged in 2019-02, with the labels that each got.

#269 LayoutEditor: Update for the default/custom split
  package.json
  src/renderer/App.js
  src/renderer/i18n/en.js
  src/renderer/i18n/hu.js
  src/renderer/screens/LayoutEditor.js
  yarn.lock
Labels: enhancement, page: keymap editor

#60 Automatic builds on push
  .travis.yml
  package.json
  tools/get-artifact
  tools/preinstall.js
  tools/s3-upload.js
Labels: enhancement, pending, question

#275 KeyboardSelect: Support devices that share the same VID+PID
  package.json
  src/renderer/screens/KeyboardSelect.js
  yarn.lock
Labels: enhancement, hardware support, pending

#274 tools/s3-upload: Redirect Chrysalis/latest/Chrysalis.*
  tools/s3-upload.js
Labels: enhancement, pending

#273 LayoutEditor update to support legacy firmware
  package.json
  src/renderer/App.js
  src/renderer/screens/LayoutEditor.js
  yarn.lock
Labels: bug, enhancement, page: keymap editor, pending

#279 Update all the shipped firmware
  static/EZ/ErgoDox/default.hex
  static/EZ/ErgoDox/experimental.hex
  static/Keyboardio/Model01/default.hex
  static/Keyboardio/Model01/experimental.hex
  static/Technomancy/Atreus/default.hex
  static/Technomancy/Atreus/experimental.hex
Labels: bug, enhancement, hardware support, pending

#280 Add a tool to update the screenshot
  data/screenshot.png
  tools/update-screenshot.sh
Labels: enhancement, pending

#278 README: Add AppImage & DMG downloads for the latest build
  README.md
Labels: enhancement, pending

#282 travis: Disable filter_secrets
  .travis.yml
Labels: enhancement, pending

#284 README.md: Add a windows .exe download badge
  README.md
Labels: enhancement, pending

#267 Refactoring for more modularity
  package.json
  src/renderer/App.js
  src/renderer/components/BoardMenu.js
  src/renderer/components/ChatMenuItem.js
  src/renderer/components/FlashMenuItem.js
  src/renderer/components/Header.js
  src/renderer/components/MainMenu/ChatMenuItem.js
  src/renderer/components/MainMenu/ColormapMenuItem.js
  src/renderer/components/MainMenu/ExitMenuItem.js
  src/renderer/components/MainMenu/FeedbackMenuItem.js
  src/renderer/components/MainMenu/FlashMenuItem.js
  src/renderer/components/MainMenu/KeyboardSelectMenuItem.js
  src/renderer/components/MainMenu/KeymapMenuItem.js
  src/renderer/components/MainMenu/MainMenu.js
  src/renderer/components/MainMenu/SettingsMenuItem.js
  src/renderer/components/MainMenu/WelcomeMenu.js
  src/renderer/routerHistory.js
  src/renderer/screens/KeyboardSelect.js
  src/renderer/screens/Welcome.js
  src/renderer/utils/openURL.js
  src/styles/keymap.css
  yarn.lock
Labels: enhancement

#289 Move a few less-than-common settings from LayoutEditor to Settings
  package.json
  src/renderer/i18n/en.js
  src/renderer/i18n/hu.js
  src/renderer/screens/LayoutEditor.js
  src/renderer/screens/Settings.js
  yarn.lock
Labels: bug, enhancement, pending

#300 Preparations for 0.4.0
  NEWS.md
  package.json
Labels: enhancement, help wanted, pending

#304 When navigating, always await for it to finish
  src/renderer/App.js
  src/renderer/screens/KeyboardSelect.js
  src/renderer/screens/Welcome.js
Labels: bug, pending

#305 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: enhancement

#308 SaveChangesButton: Change the icon to something more obvious
  src/renderer/components/Header.js
  src/renderer/components/SaveChangesButton.js
Labels: enhancement, pending

#309 LayoutEditor: Make the initial layer selection more robust
  src/renderer/screens/LayoutEditor.js
Labels: bug, page: keymap editor, pending

#310 App.js: Fix onKeyboardConnect()'s navigate targets
  src/renderer/App.js
  src/renderer/screens/KeyboardSelect.js
Labels: bug, pending

#311 Splitography support
  package.json
  src/renderer/screens/FirmwareUpdate.js
  static/SOFTHRUF/Splitography/default.hex
  static/SOFTHRUF/Splitography/experimental.hex
  yarn.lock
Labels: enhancement, hardware support, pending

#317 MainMenu: If there's a new version of Chrysalis. notify the user
  src/renderer/components/MainMenu/MainMenu.js
  src/renderer/components/MainMenu/UpgradeMenuItem.js
  src/renderer/i18n/en.js
  src/renderer/i18n/hu.js
  src/renderer/utils/getLatestVersion.js
Labels: enhancement, pending

#328 Lift ConfirmationDialog out into its own component
  src/renderer/components/ConfirmationDialog.js
  src/renderer/screens/Editor.js
Labels: enhancement, pending

#327 KeyboardSettings: Support the in-context appbar
  src/renderer/App.js
  src/renderer/screens/KeyboardSettings.js
Labels: bug, pending

#325 MainMenu: Fix a possible location mismatch
  src/renderer/components/MainMenu/MainMenu.js
Labels: bug, pending

#295 Better keymap sizing
  src/styles/keymap.css
Labels: bug, help wanted, pending, question

#332 Preferences: Save the language setting
  src/renderer/App.js
  src/renderer/screens/Preferences.js
Labels: enhancement, pending

#334 Update the screenshot
  data/screenshot.png
Labels: enhancement, pending

#337 Do not ask for confirmation when saving
  src/renderer/App.js
  src/renderer/components/Header.js
Labels: bug, pending

#338 App: Do the Editor / Welcome routing in `onKeyboardConnect`
  src/renderer/App.js
  src/renderer/screens/KeyboardSelect.js
Labels: bug, pending

#339 Editor: Dim read-only layers a little
  src/renderer/screens/Editor.js
Labels: bug, pending, screen: editor
