Repository keyboardio/Chrysalis, pull requests merged in 2020-04, with the labels that each got.

#495 Replace our i18n solution with i18next
  package.json
  src/renderer/App.js
  src/renderer/components/BoardMenu.js
  src/renderer/components/ColorPalette/ColorPalette.js
  src/renderer/components/ConfirmationDialog.js
  src/renderer/components/Header.js
  src/renderer/components/KeySelector/KeySelector.js
  src/renderer/components/MainMenu/ChatMenuItem.js
  src/renderer/components/MainMenu/ColormapMenuItem.js
  src/renderer/components/MainMenu/EditorMenuItem.js
  src/renderer/components/MainMenu/ExitMenuItem.js
  src/renderer/components/MainMenu/FeedbackMenuItem.js
  src/renderer/components/MainMenu/FlashMenuItem.js
  src/renderer/components/MainMenu/MainMenu.js
  src/renderer/components/MainMenu/PreferencesMenuItem.js
  src/renderer/components/MainMenu/UpgradeMenuItem.js
  src/renderer/components/MainMenu/WelcomeMenu.js
  src/renderer/components/SaveChangesButton.js
  src/renderer/i18n.js
  src/renderer/i18n/en.js
  src/renderer/i18n/hu.js
  src/renderer/index.js
  src/renderer/screens/Editor/CopyFromDialog.js
  src/renderer/screens/Editor/Editor.js
  src/renderer/screens/Editor/ImportExportDialog/ImportExportDialog.js
  src/renderer/screens/Editor/ImportExportDialog/LoadDefaultKeymap.js
  src/renderer/screens/Editor/KeySelector.js
  src/renderer/screens/FirmwareUpdate.js
  src/renderer/screens/KeyboardSelect.js
  src/renderer/screens/Preferences.js
  src/renderer/screens/Preferences/KeyboardSettings.js
  src/renderer/screens/Welcome.js
  yarn.lock
Labels: enhancement

#497 Editor: Support cases where we have a colormap only
  src/renderer/App.js
  src/renderer/i18n/en.js
  src/renderer/i18n/hu.js
  src/renderer/screens/Editor/Editor.js
Labels: bug, pending, screen: editor

#494 Add Num Lock key
  src/api/keymap/db/miscellaneous.js
Labels: bug, screen: editor

#498 keymap: Move the various *Lock keys to modifiers
  src/api/keymap/db/miscellaneous.js
  src/api/keymap/db/modifiers.js
  src/api/keymap/db/punctuation.js
Labels: enhancement, pending, screen: editor

#493 Add a progress bar to the FirmwareUpdate screen
  src/api/flash/index.js
  src/api/hardware-keyboardio-atreus2/index.js
  src/api/hardware-keyboardio-model01/index.js
  src/renderer/i18n/en.js
  src/renderer/i18n/hu.js
  src/renderer/screens/FirmwareUpdate.js
Labels: enhancement, pending, screen:flasher

#502 KeyboardSelect: Check device permissions on Linux
  src/api/focus/index.js
  src/renderer/i18n/en.js
  src/renderer/screens/KeyboardSelect.js
Labels: bug, pending

#466 Optionally disable the sandbox on the AppImage build
  build/afterPackHook.js
  build/launcher.sh
  package.json
Labels: bug, enhancement

#506 Do include the contents of static/ in production builds
  package.json
Labels: bug

#507 Flashing process fixes
  src/api/flash/index.js
  src/api/focus/index.js
  src/renderer/components/ConfirmationDialog.js
Labels: bug, screen:flasher

#510 Cancel the context state of the AppBar when a keyboard disconnects
  src/renderer/App.js
Labels: bug, pending
