Repository keyboardio/Chrysalis, pull requests merged in 2022-05, with the labels that each got.

#797 KeyboardSelect: When there's only one keyboard present, auto-connect
  src/renderer/screens/KeyboardSelect.js
Labels: enhancement

#796 Structured EEPROM save & restore for all keyboards
  src/api/flash/index.js
  src/api/focus/index.js
  src/api/hardware-ez-ergodox/index.js
  src/api/hardware-kbdfans-kbd4x/index.js
  src/api/hardware-keyboardio-atreus2/index.js
  src/api/hardware-keyboardio-model01/index.js
  src/api/hardware-pjrc-teensy/index.js
  src/api/hardware-softhruf-splitography/index.js
  src/api/hardware-technomancy-atreus/index.js
  src/renderer/i18n/en.js
  src/renderer/screens/FirmwareUpdate.js
  src/renderer/screens/Preferences/KeyboardSettings.js
  src/renderer/utils/deviceReset.js
Labels: bug, enhancement, screen:flasher, hardware support

#803 Editor/LayoutSharing: Offer loading layouts from backups, too.
  src/main/index.js
  src/main/ipc_backups.js
  src/main/ipc_file_io.js
  src/renderer/i18n/en.js
  src/renderer/screens/Editor/Sidebar/Overview/LayoutSharing.js
Labels: enhancement

#807 backups: Make automatic EEPROM backups device-type specific
  src/api/flash/index.js
  src/main/ipc_backups.js
  src/renderer/screens/Editor/Sidebar/Overview/LayoutSharing.js
Labels: bug

#805 api/focus: Do not send unknown requests
  src/api/focus/index.js
  src/renderer/ActiveDevice.js
Labels: enhancement

#833 We no longer use `@electron/remote`, lets drop it
  package.json
  src/main/index.js
  yarn.lock
Labels: dependencies

#835 Assorted Firmware Upgrade UX fixes
  src/renderer/screens/FirmwareUpdate.js
Labels: bug, enhancement

#830 KeyboardSelect: Pre-select the active device (if any)
  src/renderer/ActiveDevice.js
  src/renderer/screens/KeyboardSelect.js
Labels: bug

#832 LayoutCard: Use the colormap too when rendering, if available
  src/renderer/i18n/en.js
  src/renderer/screens/LayoutCard.js
  src/renderer/screens/Preferences/UserInterface.js
Labels: enhancement

#839 ChangeLog: Add vertical margins
  src/renderer/screens/ChangeLog.js
Labels: bug

#841 Remove unused dependencies
  package.json
  src/api/hardware-keyboardio-atreus2/components/Keymap.js
  src/renderer/screens/Preferences.js
  yarn.lock
Labels: dependencies

#837 Teach the sidebar to hide unavailable functionality by default
  src/api/focus/index.js
  src/renderer/ActiveDevice.js
  src/renderer/hooks/usePluginVisibility.js
  src/renderer/i18n/en.js
  src/renderer/screens/Editor/Sidebar/LayerKeys.js
  src/renderer/screens/Editor/Sidebar/LeaderKeys.js
  src/renderer/screens/Editor/Sidebar/MacroKeys.js
  src/renderer/screens/Editor/Sidebar/Modifiers.js
  src/renderer/screens/Editor/Sidebar/MouseKeys.js
  src/renderer/screens/Editor/Sidebar/OneShotKeys.js
  src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
  src/renderer/screens/Editor/Sidebar/SpaceCadetKeys.js
  src/renderer/screens/Editor/Sidebar/StenoKeys.js
  src/renderer/screens/Editor/Sidebar/TapDanceKeys.js
  src/renderer/screens/Preferences/UserInterface.js
Labels: enhancement

#840 Bump our Electron dependency to 17.4.6
  package.json
  yarn.lock
Labels: dependencies

#851 Upgrade to Electron 19, the current production release.
  package.json
  yarn.lock
Labels: dependencies

#859 MacroEditor: Close the editor when pressing Escape
  src/renderer/screens/Editor/Macros/MacroEditor.js
Labels: enhancement

#857 Editor: Prevent opening the macro editor if we don't support macros
  src/renderer/screens/Editor/Editor.js
Labels: bug

#838 Move the host layout selection to Preferences
  src/renderer/i18n/en.js
  src/renderer/screens/Editor/Editor.js
  src/renderer/screens/Editor/Sidebar.js
  src/renderer/screens/Editor/Sidebar/LogicalLayout.js
  src/renderer/screens/Preferences/LayoutSelect.js
  src/renderer/screens/Preferences/UserInterface.js
Labels: enhancement

#854 Model100: Add a layout library for the Model100 too
  static/Keyboardio/Model100/layouts/colemak.json
  static/Keyboardio/Model100/layouts/dvorak.json
  static/Keyboardio/Model100/layouts/qwerty.json
Labels: bug, hardware support

#855 Model100: Adjust the firmware update instructions
  src/renderer/i18n/en.js
Labels: bug, hardware support

#875 Improve our theme system
  src/main/index.js
  src/main/ipc_nativetheme.js
  src/renderer/App.js
  src/renderer/components/GlobalContext.js
  src/renderer/i18n/en.js
  src/renderer/screens/Preferences/ui/LookAndFeelPreferences.js
  src/renderer/utils/darkMode.js
Labels: enhancement

#872 Editor: Hide parts of the sidebar when the macro editor is open
  src/renderer/screens/Editor/Editor.js
  src/renderer/screens/Editor/Sidebar.js
  src/renderer/screens/Editor/Sidebar/Colormap.js
  src/renderer/screens/Editor/Sidebar/Overview.js
  src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
  src/renderer/screens/Editor/Sidebar/StenoKeys.js
  src/renderer/screens/Editor/Sidebar/TapDanceKeys.js
Labels: bug

#871 Preferences: Move the EscapeOneShot preferences here
  src/renderer/i18n/en.js
  src/renderer/screens/Editor/Sidebar/OneShotKeys.js
  src/renderer/screens/Preferences/MyKeyboard.js
  src/renderer/screens/Preferences/keyboard/PluginPreferences.js
  src/renderer/screens/Preferences/keyboard/plugins/EscapeOneShot.js
Labels: bug

#870 Update a few package resolutions to make dependabot happy
  package.json
  yarn.lock
Labels: dependencies

#878 Editor: Justify the color picker on the sidebar to the center
  src/renderer/screens/Editor/Sidebar/Colormap.js
Labels: bug
