Repository keyboardio/Chrysalis, pull requests merged in 2022-10, with the labels that each got.

#1129 Editor: When changing layers, ensure that the selected key is in sync
  src/renderer/screens/Editor/Editor.js
Labels: bug

#1135 udev rules: ENV doesn't support := operator
  static/udev/60-kaleidoscope.rules
Labels: bug

#1144 FirmwareUpdate: Rework how we do factory resets
  src/api/flash.js
  src/api/flash/AVRGirlFlasher.js
  src/api/flash/DFUProgrammerFlasher.js
  src/api/flash/DFUUtilFlasher.js
  src/api/flash/FocusCommands.js
  src/api/flash/TeensyFlasher.js
  src/api/flash/utils.js
  src/api/focus.js
  src/api/hardware-ez-ergodox/index.js
  src/api/hardware-keyboardio-atreus2/index.js
  src/api/hardware-keyboardio-model01/index.js
  src/api/hardware-softhruf-splitography/index.js
  src/api/hardware-technomancy-atreus/index.js
  src/api/hardware/index.js
  src/renderer/ActiveDevice.js
  src/renderer/App.js
  src/renderer/i18n/en.json
  src/renderer/i18n/nl.json
  src/renderer/screens/FirmwareUpdate.js
  src/renderer/screens/FirmwareUpdate/FlashNotification.js
Labels: bug, enhancement, hardware support

#1156 Assorted fixes for different whitescreen scenarios
  src/api/focus/colormap.js
  src/renderer/components/Toast.js
  src/renderer/screens/Editor/Sidebar/Colormap.js
  src/renderer/screens/Editor/Sidebar/Overview.js
  src/renderer/screens/Preferences/keyboard/KeyboardLayerPreferences.js
Labels: bug

#1157 ActiveDevice: When removing from the cache, delete the entire key
  src/renderer/ActiveDevice.js
Labels: bug

#1164 api/focus: Guard keymap pulling against zero-sized keymaps
  src/api/focus/keymap.js
Labels: bug

#1166 Editor: Always show the "Copy layer" and "Paste layer" buttons
  src/renderer/screens/Editor/Sidebar/Overview.js
Labels: bug

#1172 Editor: Layer copy & paste should not depend on Colormap
  src/renderer/screens/Editor/Editor.js
Labels: bug

#1176 Editor: Show the context bar after pasting a layer
  src/renderer/screens/Editor/Editor.js
Labels: bug

#1143 Add Mouse Key configuration support to Preferences
  src/api/focus.js
  src/api/focus/keymap/db/base/mousekeys.js
  src/renderer/ActiveDevice.js
  src/renderer/hooks/usePluginEffect.js
  src/renderer/i18n/en.json
  src/renderer/screens/Editor/Sidebar/MouseKeys.js
  src/renderer/screens/Editor/components/KeyButton.js
  src/renderer/screens/Preferences/components/PreferenceWithHeading.js
  src/renderer/screens/Preferences/keyboard/PluginPreferences.js
  src/renderer/screens/Preferences/keyboard/plugins/MouseKeys.js
Labels: enhancement

#1182 Improve the robustness of flashing a little
  src/api/flash.js
  src/api/focus.js
Labels: bug

#1168 CI: Add a workflow to build & publish unsigned pull request artifacts
  .github/workflows/pull-requests.yml
  tools/pr-number
  tools/preinstall.js
Labels: enhancement

#1153 cldr: Pull the Colemak layout from the osx set
  tools/precompile/cldr_data.mjs
Labels: enhancement

#1185 Editor/Sidebar: Remove the auto-close/auto-open behaviour
  src/renderer/screens/Editor/Sidebar/BlankKeys.js
  src/renderer/screens/Editor/Sidebar/BrightnessKeys.js
  src/renderer/screens/Editor/Sidebar/Colormap.js
  src/renderer/screens/Editor/Sidebar/CustomKey.js
  src/renderer/screens/Editor/Sidebar/LayerKeys.js
  src/renderer/screens/Editor/Sidebar/MediaKeys.js
  src/renderer/screens/Editor/Sidebar/Modifiers.js
  src/renderer/screens/Editor/Sidebar/MouseKeys.js
  src/renderer/screens/Editor/Sidebar/OneShotKeys.js
  src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
  src/renderer/screens/Editor/Sidebar/VolumeKeys.js
  src/renderer/screens/Editor/components/CategorySelector.js
  src/renderer/screens/Editor/components/Collapsible.js
Labels: bug

#1184 ci: Update most of the Actions we use
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/pull-requests.yml
Labels: bug

#1190 api/focus: Add all the commands we can potentially backup
  src/api/focus.js
Labels: enhancement

#1187 Preferences: OneShot configuration support
  src/renderer/ActiveDevice.js
  src/renderer/i18n/en.json
  src/renderer/screens/Preferences/components/PluginSliderWithInput.js
  src/renderer/screens/Preferences/components/PreferenceWithHeading.js
  src/renderer/screens/Preferences/keyboard/PluginPreferences.js
  src/renderer/screens/Preferences/keyboard/plugins/EscapeOneShot.js
  src/renderer/screens/Preferences/keyboard/plugins/MouseKeys.js
  src/renderer/screens/Preferences/keyboard/plugins/OneShot.js
Labels: enhancement

#1200 Fix the colormap importing via backup & restore
  src/renderer/screens/Editor/Editor.js
  src/renderer/screens/Editor/Sidebar.js
  src/renderer/screens/Editor/Sidebar/LayoutSharing.js
  src/renderer/screens/Editor/Sidebar/Overview.js
Labels: bug

#1197 ci: Only run the publish step for PRs when the source repo is ours
  .github/workflows/pull-requests.yml
Labels: bug

#1202 LayoutSharing: Do not offer backups for import for now
  src/renderer/screens/Editor/Sidebar/LayoutSharing.js
Labels: bug

#1215 Do not offer snapshot firmware on release versions of Chrysalis
  src/main/ipc_firmware.js
Labels: bug
