Repository keyboardio/Chrysalis, pull requests merged in 2022-09, with the labels that each got.

#1039 api/focus: Handle situations where we have incoming data without a callback
  src/api/focus.js
Labels: bug

#1040 FirmwareUpdate: Change the factory reset confirmation label to Continue
  src/renderer/screens/FirmwareUpdate.js
Labels: enhancement

#1042 hardware/atreus2: Display the main legend in big letters if it's a single letter
  src/api/hardware-keyboardio-atreus2/components/Keymap.js
Labels: enhancement

#1046 Keyboard104: Remove an unnecessary keyCode
  src/api/focus/keymap/db/base.js
  src/renderer/screens/Editor/Keyboard104.js
Labels: bug

#1048 Preferences: SpaceCadet support
  src/api/focus.js
  src/renderer/i18n/en.json
  src/renderer/screens/Preferences/keyboard/PluginPreferences.js
  src/renderer/screens/Preferences/keyboard/plugins/SpaceCadet.js
Labels: enhancement

#1050 Preferences: Use the same terminology for "OneShot" as on the Editor
  src/renderer/i18n/en.json
Labels: enhancement

#1051 api/flash: Capture and log errors when trying to spawn a child process
  src/api/flash/DFUProgrammerFlasher.js
  src/api/flash/DFUUtilFlasher.js
Labels: bug, hardware support

#1053 Model100: Include a Colemak DH layout
  static/Keyboardio/Model100/layouts/colemak-dh.json
Labels: enhancement

#1058 @api/focus: Do not drain the serial port while writing request parts
  src/api/focus.js
Labels: bug

#1078 Display breaking news for Model 100 owners on the keyboard selection screen
  src/renderer/breaking-news.js
  src/renderer/breaking-news/firmware-0.90.1.js
  src/renderer/components/BreakingNews.js
  src/renderer/i18n/en.json
  src/renderer/screens/KeyboardSelect.js
Labels: enhancement, hardware support

#1075 Enable firmware auto-update by default
  src/main/ipc_firmware.js
  src/renderer/hooks/useFirmwareAutoUpdate.js
  src/renderer/screens/Preferences/AutoUpdate.js
Labels: enhancement

#1080 When using eeprom.erase, return after 10 seconds
  src/renderer/screens/Preferences/MyKeyboard.js
  src/renderer/screens/Preferences/keyboard/AdvancedKeyboardPreferences.js
  src/renderer/utils/clearEEPROM.js
Labels: bug

#1100 Prevent saving & display an alert when layernames take too much space
  src/api/focus/layernames.js
  src/renderer/i18n/en.json
  src/renderer/screens/Editor/Editor.js
  src/renderer/screens/Editor/components/LayerNamesStorageAlert.js
Labels: bug

#1102 Change how we let users perform a full factory reset, making the option more prominent.
  src/renderer/i18n/en.json
  src/renderer/screens/FirmwareUpdate.js
Labels: enhancement

#1106 * Add support for Apple's Screen Lock, Globe, Exposé and Mission Control keys.
  src/api/focus/keymap/db/base.js
  src/api/focus/keymap/db/base/lang_intl.js
  src/api/focus/keymap/db/base/platform_apple.js
  src/renderer/i18n/en.json
  src/renderer/screens/Editor/Sidebar.js
  src/renderer/screens/Editor/Sidebar/LanguageKeys.js
  src/renderer/screens/Editor/Sidebar/PlatformAppleKeys.js
Labels: enhancement

#1104 The existing firmware update screen is very verbose and not very space efficient.
  src/renderer/i18n/en.json
  src/renderer/screens/FirmwareUpdate.js
  src/renderer/screens/FirmwareUpdate/FirmwareSelect.js
Labels: enhancement

#1115 api/focus: Do not close the port when receiving a close event
  src/api/focus.js
Labels: bug

#1113 Perform some sanity checks during startup
  src/renderer/App.js
  src/renderer/i18n/en.json
  src/renderer/routerHistory.js
  src/renderer/screens/SanityCheck.js
Labels: enhancement

#1118 Couple of fixes for secondary action modifiers
  src/api/focus/keymap/db/base/dualuse.js
  src/renderer/screens/Editor/Sidebar/Modifiers.js
  src/renderer/screens/Editor/Sidebar/SecondaryFunction.js
Labels: bug

#1120 Editor: Do not disable saving if LayerNames is not in use
  src/renderer/screens/Editor/Editor.js
Labels: bug

#1123 styles/keymap.css: Disable user-select for the keymap SVGs
  src/styles/keymap.css
Labels: bug
